# Rename this file to configuration.yml

machine_name: yourmachinename

hostname: hostname

ssh_private: keys/id_rsa
ssh_public: keys/id_rsa.pub

# Box Setup
box: bento/ubuntu-16.04
box_memory: 8192
box_cpus: 2

# Sync Folders.
sync:
  - host: /path/to/host
    guest: /path/in/guest
    id: uniqueIdentifier
    
