FROM mysql/mysql-server:5.6
MAINTAINER Christophe G <christophe@highwaythreesolutions.com>

# Define environment variable
EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD root

ENV MYSQL_USER user
ENV MYSQL_PASSWORD user