name: TEMPLATE
enabled: false

# build_compose: 
services:
    service-name:
        build: /guest-machine/path/to/the/dockerfilefolder
        image: image-name
        volumes:
            - /host-machine/www:/guest-machine/www
        domains: 
            - testapp.dev 
            - test.testapp.dev 
            - another.testapp.dev 
        networks:
            - networkname
